#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-DateTime-Format-W3CDTF
Version  : 0.07
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/G/GW/GWILLIAMS/DateTime-Format-W3CDTF-0.07.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/G/GW/GWILLIAMS/DateTime-Format-W3CDTF-0.07.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libx/libxml-feed-perl/libxml-feed-perl_0.53+dfsg-1.debian.tar.xz
Summary  : 'Parse and format W3CDTF datetime strings'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0 GPL-1.0 Artistic-1.0-Perl Artistic-1.0-cl8 GPL-1.0 GPL-2.0
Requires: perl-DateTime-Format-W3CDTF-license
Requires: perl-DateTime-Format-W3CDTF-man
Requires: perl(DateTime)
BuildRequires : perl(DateTime)

%description
NAME
DateTime::Format::W3CDTF - Parse and format W3CDTF datetime strings
SYNOPSIS
use DateTime::Format::W3CDTF;

%package license
Summary: license components for the perl-DateTime-Format-W3CDTF package.
Group: Default

%description license
license components for the perl-DateTime-Format-W3CDTF package.


%package man
Summary: man components for the perl-DateTime-Format-W3CDTF package.
Group: Default

%description man
man components for the perl-DateTime-Format-W3CDTF package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n DateTime-Format-W3CDTF-0.07
mkdir -p %{_topdir}/BUILD/DateTime-Format-W3CDTF-0.07/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/DateTime-Format-W3CDTF-0.07/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-DateTime-Format-W3CDTF
cp LICENSE %{buildroot}/usr/share/doc/perl-DateTime-Format-W3CDTF/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-DateTime-Format-W3CDTF/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/DateTime/Format/W3CDTF.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-DateTime-Format-W3CDTF/LICENSE
/usr/share/doc/perl-DateTime-Format-W3CDTF/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/DateTime::Format::W3CDTF.3
